export default () => ({
  brand: [
    { name: "Pitney Bows" },
    { name: "Brother" },
    { name: "Canon" },
    { name: "Riso" },
    { name: "Hewlett Packard" },
    { name: "Dell" },
    { name: "Epson" },
    { name: "Imajistics" },
    { name: "Kyosera" },
    { name: "Lexmark" },
    { name: "Panasonic" },
    { name: "Ricoh" },
    { name: "Samsung" },
    { name: "Troy" },
    { name: "Zerox" },
  ],
  products: [
    {
      id: "Item #793-5",
      name: "Red Ink Cartridge (35 ml) for DM100™, DM200™ and SendPro® C and SendPro®+",
      cost: "$109.99",
      img: "https://www.pitneybowes.com/content/dam/espots/us-ca/products/7xx-799/793-5-front%20(1).png",
    },
    {
      id: "Item #797-M",
      name: "Red Ink Cartridge for mailstation2™",
      cost: " $79.99",
      img: "https://www.pitneybowes.com/content/dam/espots/us-ca/products/7xx-799/797-M-front%20(1).png",
    },
    {
      id: "Item #765-9",
      name: "Red Ink Cartridge for SendPro® C Auto, DM300C™ & DM400C™ Series",
      cost: "$159.99",
      img: "https://www.pitneybowes.com/content/dam/espots/us-ca/products/7xx-799/765-9-front%20(1).png",
    },
    {
      id: "Item #787-1",
      name: "Red Ink Cartridge (Production) for SendPro® P / Connect+® Series Mailing Systems",
      cost: " $319.99",
      img: "https://www.pitneybowes.com/content/dam/espots/us-ca/products/7xx-799/787-1-front%20(1).png",
    },
    {
      id: "Item #797-0",
      name: "Red Ink Cartridge for mailstation™",
      cost: "$79.99",
      img: "https://www.pitneybowes.us/suppliesui/pbui/site-content/images/large/en_US/797-0.jpg",
    },
    {
      id: "Item #625-0",
      name: "SendPro® C Auto, DM300, DM400 Series Postage Tape Strips",
      cost: "$79.99",
      img: "https://www.pitneybowes.us/suppliesui/pbui/site-content/images/large/en_US/625-0.jpg",
    },
    {
      id: "Item #787-8",
      name: "Red Ink Cartridge (Large) for SendPro® P / Connect+® Series Mailing Systems",
      cost: "$209.99",
      img: "https://www.pitneybowes.us/suppliesui/pbui/site-content/images/large/en_US/787-8.jpg",
    },
    {
      id: "Item #SL-798-0",
      name: "Red Ink Cartridge (17 ml) for SendPro® C and SendPro®+",
      cost: "$64.99",
      img: "https://www.pitneybowes.com/content/dam/espots/us-ca/products/7xx-799/SL-798-0-front%20(2).png",
    },
    {
      id: "Item #620-9",
      name: "Postage Tape Sheets for mailstation, DM100 Series, SendPro® Mailstation, SendPro® C and +",
      cost: "$79.99",
      img: "https://www.pitneybowes.us/suppliesui/pbui/site-content/images/large/en_US/620-9.jpg",
    },
    {
      id: "Item #613-H",
      name: "SendPro® P / Connect+® Series Self-Adhesive Tape Rolls",
      cost: "$159.99",
      img: "https://www.pitneybowes.us/suppliesui/pbui/site-content/images/large/en_US/613-H.jpg",
    },
  ],
});
